server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-3tseapf5ui-stack-awsebrdsdatabase-qb1m0l1sgoqi.cyw7mh2gmz45.eu-west-1.rds.amazonaws.com:5432/ebdb
    username: amigoscode
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  main:
    web-application-type: servlet